In [1]:
import numpy as np
from activation import Softmax

# Backpropagation

### forwardpass of single neuron

In [2]:
x=[1,2,3]
w=[-3,-1,2]
b=1

xw0=x[0]*w[0]
xw1=x[1]*w[1]
xw2=x[2]*w[2]

z=xw0+xw1+xw2+b  #after adding the bias 

#lets pass through the activation function
z=max(0,z)

### lets check out the backpropagation

In [3]:
x=[1,-2,3]
w=[-3,-1,2]
b=1

xw0=x[0]*w[0]
xw1=x[1]*w[1]
xw2=x[2]*w[2]

z=xw0+xw1+xw2+b

#lets pass it through the relu activation function
y=max(0,z)

#let check the backpropagation

#the value of the Relu 
dvalue=1  

#the derivative from the next layer and Relu function
drelu_dz=dvalue*(1 if z>0 else 0)

#lets print our findings
print(drelu_dz)

#lets backpropagate through the summation
dz_dxw0=1
drelu_xw0=drelu_dz*dz_dxw0

dz_dxw1=1
drelu_xw1=drelu_dz*dz_dxw1

dz_dxw2=1
drelu_xw2=drelu_dz*dz_dxw2

dz_db=1
drelu_db=drelu_dz*dz_db
#lets print ourfindings
print(drelu_xw0,drelu_xw1,drelu_xw2,drelu_db)

#lets backpropagate through the inputs
dxw0_dx0=w[0]
drelu_dx0=drelu_dz*dz_dxw0*dxw0_dx0

dxw1_dx1=w[1]
drelu_dx1=drelu_dz*dz_dxw1*dxw1_dx1

dxw2_dx2=w[2]
drelu_dx2=drelu_dz*dz_dxw2*dxw2_dx2

#lets backpropgate through the weights
dxw0_dw0=x[0]
drelu_dw0=drelu_dz*dz_dxw0*dxw0_dw0

dxw1_dw1=x[1]
drelu_dw1=drelu_dz*dz_dxw1*dxw1_dw1

dxw2_dw2=x[2]
drelu_dw2=drelu_dz*dz_dxw2*dxw2_dw2


#lets print our backpropgated values
print(drelu_dx0,drelu_dw0,drelu_dx1,drelu_dw1,drelu_dx2,drelu_dw2)

1
1 1 1 1
-3 1 -1 -2 2 3


In [4]:
# the output
print(y)

6


#### yay

In [5]:
#our gradients are
dw=[drelu_dw0,drelu_dw1,drelu_dw2]
dx=[drelu_dx0,drelu_dx1,drelu_dx2]
db=drelu_db

In [6]:
print(w)
print(b)

[-3, -1, 2]
1


In [7]:
print(type(w))
print(type(b))

<class 'list'>
<class 'int'>


In [8]:
# lets update the parameter of the values
w[0]+=-0.001*dw[0]
w[1]+=-0.001*dw[1]
w[2]+=-0.001*dw[2]
b+=-0.001*db

#lets train our model again and see
xw0=x[0]*w[0]
xw1=x[1]*w[1]
xw2=x[2]*w[2]
z=xw0+xw1+xw2+b
y=max(0,z)

#output
print(y)

5.985


# move on to layer that has multiple neurons

In [9]:
#backpropagated from next layers
dvalues=np.array([[1,1,1]])

weights=np.array([
    [0.2,0.8,-0.5,1],
    [0.5,-0.91,0.26,-0.5],
    [-0.26,-0.27,0.17,0.87]
]).T    # Notice:we are transposing the values here please pay attention here


#lets implement the backpropagation with respect to the inputs
dx0=sum(weights[0])*dvalues[0]
dx1=np.sum(weights[1])*dvalues[0]
dx2=np.sum(weights[2])*dvalues[0]
dx3=np.sum(weights[3])*dvalues[0]

dinputs=np.array([dx0,dx1,dx2,dx3]) #the derivatives of all the inputs
print(dinputs)

[[ 0.44  0.44  0.44]
 [-0.38 -0.38 -0.38]
 [-0.07 -0.07 -0.07]
 [ 1.37  1.37  1.37]]


In [10]:
print(np.sum(weights[0])*1)

0.43999999999999995


In [11]:
temp=np.array([[1,2,3]])
print(temp[0])

[1 2 3]


## more effificent way of making the derivartive

In [12]:
#a better way of running this code 
dx0=sum(weights[0]*dvalues[0])
dx1=sum(weights[1]*dvalues[0])
dx2=sum(weights[2]*dvalues[0])
dx3=sum(weights[3]*dvalues[0])

dinputs=np.array([dx0,dx1,dx2,dx3])
print(dinputs)

[ 0.44 -0.38 -0.07  1.37]


## using numpy

In [13]:
#lets ease the calculation using numpy
dinputs=np.dot(dvalues[0],weights.T)   # 1x3 weights 3x4
print(dinputs)

[ 0.44 -0.38 -0.07  1.37]


In [14]:
weights.shape,dvalues.shape

((4, 3), (1, 3))

In [15]:
temp=np.dot(weights,dvalues[0].T)
#print(temp,temp.shape)
#print()
print(temp.T)

[ 0.44 -0.38 -0.07  1.37]


# handling batch of data during backpropagation

## derivating with respect to inputs

In [16]:
#derivatives from the next layer
dvalues=np.array([
    [1,1,1],
    [2,2,2],
    [3,3,3]
])
weights=np.array([
    [0.2,0.8,-0.5,1],
    [0.5,-0.91,0.26,-0.5],
    [-0.26,-0.27,0.17,0.87]
]).T

dinputs=np.dot(dvalues,weights.T)  #dvalues shape is=3x3 and weights is 4x3
print(dinputs)

[[ 0.44 -0.38 -0.07  1.37]
 [ 0.88 -0.76 -0.14  2.74]
 [ 1.32 -1.14 -0.21  4.11]]


## lets derivate with respect to the weights

In [17]:
#the values that is backpropagated through the network
dvalues=np.array([
    [1,1,1],
    [2,2,2],
    [3,3,3]
])

#inputs
inputs=np.array([
    [1,2,3,2.5],
    [2,5,-1,2],
    [-1.5,2.7,3.3,-0.8]
])

dweights=np.dot(inputs.T,dvalues)
print(dweights)

[[ 0.5  0.5  0.5]
 [20.1 20.1 20.1]
 [10.9 10.9 10.9]
 [ 4.1  4.1  4.1]]


# derivate with respect to the bias

In [18]:
#lets go
biases=np.array([[2,3,0.5]])

dvalues=np.array([
    [1,1,1],
    [2,2,2],
    [3,3,3]
])

dbias=np.sum(dvalues,axis=0,keepdims=True)  #summing column wise here and makes it row vector
print(dbias.shape)

(1, 3)


# derivate with respect to the Relu function

In [19]:
# z=np.array([
#     [1,2,-3,-4],
#     [2,-7,-1,3],
#     [-1,2,5,-1]
# ])
# print(z)

# dvalues=np.array([
#     [1,2,3,4],
#     [5,6,7,8],
#     [9,10,11,12]
# ])

# print(dvalues)

# #les setup the shape of the derivative with relu
# drelu=np.zeros_like(z)
#print(drelu.shape)

# def sth(z):
#      return list(map(lambda x:1 if x > 0 else 0 , z))
    
# drelu_res = map(sth, z)
# drelu[z>0]=1
# for i in z:
#     print(i)
#drelu = [[1 for j in i if j > 0] for i in z]
# for i, k in enumerate(z):
#     for j, x in enumerate(k):
#         if x > 0: drelu[i][j] = 1
            
# print(type(drelu))
# print(list(drelu_res))

#print(drelu)
# drelu*=dvalues
#print(drelu)

In [20]:
z=np.array([
    [1,2,-3,-4],
    [2,-7,-1,3],
    [-1,2,5,-1]
])

dvalues=np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

#set the shape
drelu=np.zeros_like(z)

#make mappping fromt the input to the gradient
drelu[z>0]=1

drelu*=dvalues

In [21]:
print(drelu)

[[ 1  2  0  0]
 [ 5  0  0  8]
 [ 0 10 11  0]]


## another way of doing this

In [22]:
z=np.array([
    [1,2,-3,-4],
    [2,-7,-1,3],  
    [-1,2,5,-1]
])

dvalues=np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

drelu=dvalues.copy()  #if we dont copy it..it becomes pointer like data relationship
drelu[z<0]=0
print(drelu)

[[ 1  2  0  0]
 [ 5  0  0  8]
 [ 0 10 11  0]]


# lets see for batch based gradient in layers

In [23]:
#start
dvalues=np.array([
    [1,1,1],
    [2,2,2],
    [3,3,3]
])

#bacth of inputs like 3 of them hehe
inputs=np.array([
    [1,2,3,2.5],
    [2,5,-1,2],
    [-1.5,2.7,3.3,-0.8]
])
weights=np.array([
    [0.2,0.8,-0.5,1],
    [0.5,-0.91,0.26,-0.5],
    [0.26,-0.27,0.17,0.87]
]).T     #the origina shape before transpose is number of neurons by the input features

bias=np.array([[2,3,0.5]])

layer_output=np.dot(inputs,weights)+bias

relu_output=np.maximum(0,layer_output)
#print(relu_output)
drelu=dvalues.copy()
drelu[layer_output<0]=0
#print(drelu)

#lets get deep derivation using chain rul
dinputs=np.dot(drelu,weights.T)
dweights=np.dot(inputs.T,drelu)
dbiases=np.sum(drelu,axis=0)  #summing along the column

#lets update the parameter
weights+=-0.01*dweights
bias+=-0.01*dbias

# print(weights)
# print(bias)

# lets derivate loss with respect to the inputs

In [24]:
def backward(dvalues,y_true):
    samples=len(dvalues)
    
    #elements of y_true
    element=len(dvalues[0])

    #lets chake the shape
    if len(y_true.shape)==1:
        y_true=y_true.T
        y_true=np.diagflat(y_true)   #making eke

    print("hello from inside function")
    print(y_true)
    dinputs=-y_true/dvalues
    #lets normalize the gradient
    dinputs=dinputs/samples
    return dinputs

In [25]:
dvalues=np.random.randn(3,2)
y_true=np.array([[1,2,1]])

In [26]:
print(dvalues.shape,y_true.shape)

(3, 2) (1, 3)


# lets implment the softmax derivation

* the Equation for the softmax derivative looks like this:  \
 derivative= Sij*QJK-Sij*Sik   ** here the QJK stands for the kronecker delta which has the following values \
                      Sij  = 0 ==> if i=j\
                           = 1 ==> if they are not equal 

## left side of the derivative formula

In [27]:
softmax_outputs=np.array([[0.7,0.1,0.2]]).T
print(softmax_outputs)

[[0.7]
 [0.1]
 [0.2]]


In [28]:
square_shaped=np.eye(softmax_outputs.shape[0])
print(square_shaped)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [29]:
print(softmax_outputs.shape)
print(square_shaped.shape)

(3, 1)
(3, 3)


In [30]:
softmax_outputs*square_shaped

array([[0.7, 0. , 0. ],
       [0. , 0.1, 0. ],
       [0. , 0. , 0.2]])

In [31]:
# lets try using diagflat... my experiment with diagflat

# temp1=np.array([[1,2,3,4]])
# np.diagflat(temp1)

#lets try using column vector
# temp2=np.array([1,2,3,4]).reshape(-1,1)
# np.diagflat(temp2)

#lets try it on matrix format
# p=np.array([
#     [1,1,1,1],
#     [2,2,2,2],
#     [3,3,3,3]
# ])
# np.diagflat(p)

## right side of the derivative formula

In [32]:
np.dot(softmax_outputs,softmax_outputs.T)  #the result is called jacbobias matrix

array([[0.49, 0.07, 0.14],
       [0.07, 0.01, 0.02],
       [0.14, 0.02, 0.04]])

In [33]:
temp1=np.array([1,2,3])
temp2=np.array([4,5,6])
np.dot(temp1,temp2)

32

In [34]:
# lets implemnen the backprop for the softmax
class Softmax:
    def forward(self,inputs,weights):
        self.outputs=np.dot(inputs,weights.T)
        
    def backward(self,dvalues):
        self.dinputs=np.zeros_like(dvalues)
        for index,(ind_outputs,ind_dvalues) in enumerate(zip(self.outputs,dvalues)):
            #making the individual output column vector
            ind_outputs=ind_outputs.reshape(-1,1)
            left_side=np.diagfiat(ind_outputs)
            right_side=np.dot(ind_outputs,ind_outputs.T)
            jackobian_matrix=left_side-right_side
            self.dinputs[index]=np.dot(ind_dvalues,jackobian_matrix)
        return self.dinputs

In [35]:
# temp1=np.random.randn(3,3)
# temp2=np.random.randn(1,3)
# np.dot(temp1,temp2)