In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
from activation import Softmax

# Backpropagation

### forwardpass of single neuron

In [3]:
x=[1,2,3]
w=[-3,-1,2]
b=1

xw0=x[0]*w[0]
xw1=x[1]*w[1]
xw2=x[2]*w[2]

z=xw0+xw1+xw2+b  #after adding the bias 

#lets pass through the activation function
z=max(0,z)

### lets check out the backpropagation

In [4]:
x=[1,-2,3]
w=[-3,-1,2]
b=1

xw0=x[0]*w[0]
xw1=x[1]*w[1]
xw2=x[2]*w[2]

z=xw0+xw1+xw2+b

#lets pass it through the relu activation function
y=max(0,z)

#let check the backpropagation

#the value of the Relu 
dvalue=1  

#the derivative from the next layer and Relu function
drelu_dz=dvalue*(1 if z>0 else 0)

#lets print our findings
print(drelu_dz)

#lets backpropagate through the summation
dz_dxw0=1
drelu_xw0=drelu_dz*dz_dxw0

dz_dxw1=1
drelu_xw1=drelu_dz*dz_dxw1

dz_dxw2=1
drelu_xw2=drelu_dz*dz_dxw2

dz_db=1
drelu_db=drelu_dz*dz_db
#lets print ourfindings
print(drelu_xw0,drelu_xw1,drelu_xw2,drelu_db)

#lets backpropagate through the inputs
dxw0_dx0=w[0]
drelu_dx0=drelu_dz*dz_dxw0*dxw0_dx0

dxw1_dx1=w[1]
drelu_dx1=drelu_dz*dz_dxw1*dxw1_dx1

dxw2_dx2=w[2]
drelu_dx2=drelu_dz*dz_dxw2*dxw2_dx2

#lets backpropgate through the weights
dxw0_dw0=x[0]
drelu_dw0=drelu_dz*dz_dxw0*dxw0_dw0

dxw1_dw1=x[1]
drelu_dw1=drelu_dz*dz_dxw1*dxw1_dw1

dxw2_dw2=x[2]
drelu_dw2=drelu_dz*dz_dxw2*dxw2_dw2


#lets print our backpropgated values
print(drelu_dx0,drelu_dw0,drelu_dx1,drelu_dw1,drelu_dx2,drelu_dw2)

1
1 1 1 1
-3 1 -1 -2 2 3


In [5]:
# the output
print(y)

6


#### yay

In [6]:
#our gradients are
dw=[drelu_dw0,drelu_dw1,drelu_dw2]
dx=[drelu_dx0,drelu_dx1,drelu_dx2]
db=drelu_db

In [7]:
print(w)
print(b)

[-3, -1, 2]
1


In [8]:
print(type(w))
print(type(b))

<class 'list'>
<class 'int'>


In [9]:
# lets update the parameter of the values
w[0]+=-0.001*dw[0]
w[1]+=-0.001*dw[1]
w[2]+=-0.001*dw[2]
b+=-0.001*db

#lets train our model again and see
xw0=x[0]*w[0]
xw1=x[1]*w[1]
xw2=x[2]*w[2]
z=xw0+xw1+xw2+b
y=max(0,z)

#output
print(y)

5.985


# move on to layer that has multiple neurons

In [10]:
#backpropagated from next layers
dvalues=np.array([[1,1,1]])

weights=np.array([
    [0.2,0.8,-0.5,1],
    [0.5,-0.91,0.26,-0.5],
    [-0.26,-0.27,0.17,0.87]
]).T    # Notice:we are transposing the values here please pay attention here


#lets implement the backpropagation with respect to the inputs
dx0=sum(weights[0])*dvalues[0]
dx1=np.sum(weights[1])*dvalues[0]
dx2=np.sum(weights[2])*dvalues[0]
dx3=np.sum(weights[3])*dvalues[0]

dinputs=np.array([dx0,dx1,dx2,dx3]) #the derivatives of all the inputs
print(dinputs)

[[ 0.44  0.44  0.44]
 [-0.38 -0.38 -0.38]
 [-0.07 -0.07 -0.07]
 [ 1.37  1.37  1.37]]


In [11]:
print(np.sum(weights[0])*1)

0.43999999999999995


In [12]:
temp=np.array([[1,2,3]])
print(temp[0])

[1 2 3]


## more effificent way of making the derivartive

In [13]:
#a better way of running this code 
dx0=sum(weights[0]*dvalues[0])
dx1=sum(weights[1]*dvalues[0])
dx2=sum(weights[2]*dvalues[0])
dx3=sum(weights[3]*dvalues[0])

dinputs=np.array([dx0,dx1,dx2,dx3])
print(dinputs)

[ 0.44 -0.38 -0.07  1.37]


## using numpy

In [14]:
#lets ease the calculation using numpy
dinputs=np.dot(dvalues[0],weights.T)   # 1x3 weights 3x4
print(dinputs)

[ 0.44 -0.38 -0.07  1.37]


In [15]:
weights.shape,dvalues.shape

((4, 3), (1, 3))

In [16]:
temp=np.dot(weights,dvalues[0].T)
#print(temp,temp.shape)
#print()
print(temp.T)

[ 0.44 -0.38 -0.07  1.37]


# handling batch of data during backpropagation

## derivating with respect to inputs

In [17]:
#derivatives from the next layer
dvalues=np.array([
    [1,1,1],
    [2,2,2],
    [3,3,3]
])
weights=np.array([
    [0.2,0.8,-0.5,1],
    [0.5,-0.91,0.26,-0.5],
    [-0.26,-0.27,0.17,0.87]
]).T

dinputs=np.dot(dvalues,weights.T)  #dvalues shape is=3x3 and weights is 4x3
print(dinputs)

[[ 0.44 -0.38 -0.07  1.37]
 [ 0.88 -0.76 -0.14  2.74]
 [ 1.32 -1.14 -0.21  4.11]]


## lets derivate with respect to the weights

In [18]:
#the values that is backpropagated through the network
dvalues=np.array([
    [1,1,1],
    [2,2,2],
    [3,3,3]
])

#inputs
inputs=np.array([
    [1,2,3,2.5],
    [2,5,-1,2],
    [-1.5,2.7,3.3,-0.8]
])

dweights=np.dot(inputs.T,dvalues)
print(dweights)

[[ 0.5  0.5  0.5]
 [20.1 20.1 20.1]
 [10.9 10.9 10.9]
 [ 4.1  4.1  4.1]]


# derivate with respect to the bias

In [19]:
#lets go
biases=np.array([[2,3,0.5]])

dvalues=np.array([
    [1,1,1],
    [2,2,2],
    [3,3,3]
])

dbias=np.sum(dvalues,axis=0,keepdims=True)  #summing column wise here and makes it row vector
print(dbias.shape)

(1, 3)


# derivate with respect to the Relu function

In [20]:
# z=np.array([
#     [1,2,-3,-4],
#     [2,-7,-1,3],
#     [-1,2,5,-1]
# ])
# print(z)

# dvalues=np.array([
#     [1,2,3,4],
#     [5,6,7,8],
#     [9,10,11,12]
# ])

# print(dvalues)

# #les setup the shape of the derivative with relu
# drelu=np.zeros_like(z)
#print(drelu.shape)

# def sth(z):
#      return list(map(lambda x:1 if x > 0 else 0 , z))
    
# drelu_res = map(sth, z)
# drelu[z>0]=1
# for i in z:
#     print(i)
#drelu = [[1 for j in i if j > 0] for i in z]
# for i, k in enumerate(z):
#     for j, x in enumerate(k):
#         if x > 0: drelu[i][j] = 1
            
# print(type(drelu))
# print(list(drelu_res))

#print(drelu)
# drelu*=dvalues
#print(drelu)

In [21]:
z=np.array([
    [1,2,-3,-4],
    [2,-7,-1,3],
    [-1,2,5,-1]
])

dvalues=np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

#set the shape
drelu=np.zeros_like(z)

#make mappping fromt the input to the gradient
drelu[z>0]=1

drelu*=dvalues

In [22]:
print(drelu)

[[ 1  2  0  0]
 [ 5  0  0  8]
 [ 0 10 11  0]]


## another way of doing this

In [23]:
z=np.array([
    [1,2,-3,-4],
    [2,-7,-1,3],  
    [-1,2,5,-1]
])

dvalues=np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

drelu=dvalues.copy()  #if we dont copy it..it becomes pointer like data relationship
drelu[z<0]=0
print(drelu)

[[ 1  2  0  0]
 [ 5  0  0  8]
 [ 0 10 11  0]]


# lets see for batch based gradient in layers

In [24]:
#start
dvalues=np.array([
    [1,1,1],
    [2,2,2],
    [3,3,3]
])

#bacth of inputs like 3 of them hehe
inputs=np.array([
    [1,2,3,2.5],
    [2,5,-1,2],
    [-1.5,2.7,3.3,-0.8]
])
weights=np.array([
    [0.2,0.8,-0.5,1],
    [0.5,-0.91,0.26,-0.5],
    [0.26,-0.27,0.17,0.87]
]).T     #the origina shape before transpose is number of neurons by the input features

bias=np.array([[2,3,0.5]])

layer_output=np.dot(inputs,weights)+bias

relu_output=np.maximum(0,layer_output)
#print(relu_output)
drelu=dvalues.copy()
drelu[layer_output<0]=0
#print(drelu)

#lets get deep derivation using chain rul
dinputs=np.dot(drelu,weights.T)
dweights=np.dot(inputs.T,drelu)
dbiases=np.sum(drelu,axis=0)  #summing along the column

#lets update the parameter
weights+=-0.01*dweights
bias+=-0.01*dbias

# print(weights)
# print(bias)

# lets derivate loss(Categorical Cross Entropy) with respect to the inputs

In [25]:
def backward(dvalues,y_true):
    samples=len(dvalues)
    
    #elements of y_true
    element=len(dvalues[0])

    #lets chake the shape
    if len(y_true.shape)==1:
        y_true=y_true.T
        y_true=np.diagflat(y_true)   #making eke

    print("hello from inside function")
    print(y_true)
    dinputs=-y_true/dvalues
    #lets normalize the gradient
    dinputs=dinputs/samples
    return dinputs

In [26]:
print(temp)

[ 0.44 -0.38 -0.07  1.37]


In [27]:
dvalues=np.random.randn(3,2)
y_true=np.array([[1,2,1]])

In [28]:
print(dvalues.shape,y_true.shape)

(3, 2) (1, 3)


# lets implment the softmax derivation

* the Equation for the softmax derivative looks like this:  \
 derivative= Sij*QJK-Sij*Sik   ** here the QJK stands for the kronecker delta which has the following values \
                      Sij  = 0 ==> if i=j\
                           = 1 ==> if they are not equal 

## left side of the derivative formula

In [29]:
softmax_outputs=np.array([[0.7,0.1,0.2]]).T
print(softmax_outputs)

[[0.7]
 [0.1]
 [0.2]]


In [30]:
square_shaped=np.eye(softmax_outputs.shape[0])
print(square_shaped)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [31]:
print(softmax_outputs.shape)
print(square_shaped.shape)

(3, 1)
(3, 3)


In [32]:
softmax_outputs*square_shaped

array([[0.7, 0. , 0. ],
       [0. , 0.1, 0. ],
       [0. , 0. , 0.2]])

In [33]:
# lets try using diagflat... my experiment with diagflat

# temp1=np.array([[1,2,3,4]])
# np.diagflat(temp1)

#lets try using column vector
# temp2=np.array([1,2,3,4]).reshape(-1,1)
# np.diagflat(temp2)

#lets try it on matrix format
# p=np.array([
#     [1,1,1,1],
#     [2,2,2,2],
#     [3,3,3,3]
# ])
# np.diagflat(p)

## right side of the derivative formula

In [34]:
np.dot(softmax_outputs,softmax_outputs.T)  #the result is called jacbobias matrix

array([[0.49, 0.07, 0.14],
       [0.07, 0.01, 0.02],
       [0.14, 0.02, 0.04]])

In [35]:
temp1=np.array([1,2,3])
temp2=np.array([4,5,6])
np.dot(temp1,temp2)

32

In [36]:
# lets implemnen the backprop for the softmax
class Softmax:
    def forward(self,inputs,weights):
        self.outputs=np.dot(inputs,weights.T)
        
    def backward(self,dvalues):
        self.dinputs=np.zeros_like(dvalues)
        for index,(ind_outputs,ind_dvalues) in enumerate(zip(self.outputs,dvalues)):
            #making the individual output column vector
            ind_outputs=ind_outputs.reshape(-1,1)
            left_side=np.diagfiat(ind_outputs)
            right_side=np.dot(ind_outputs,ind_outputs.T)
            jackobian_matrix=left_side-right_side
            self.dinputs[index]=np.dot(ind_dvalues,jackobian_matrix)
        return self.dinputs

In [37]:
# temp1=np.random.randn(3,3)
# temp2=np.random.randn(1,3)
# np.dot(temp1,temp2)

In [38]:
from activation import Softmax
softmax_fn=Softmax()
inputs=np.random.randn(3,4)
softmax_fn.forward(inputs)

In [39]:
softmax_fn.outputs

array([[0.26837355, 0.27983664, 0.1968649 , 0.25492491],
       [0.36366096, 0.2847154 , 0.18851472, 0.16310892],
       [0.08648717, 0.0906067 , 0.55879017, 0.26411596]])

# common categorical cross entropy loss and softmax activation derivative

* we are going to extract the dervivative of categorical corss entropy from softmax activation function
* its simpler and faster to comupte

In [40]:
from activation import Softmax
from loss import Categorical_loss_entropy

In [41]:
class softmax_cross_entropy_loss:
    def __init__(self):
        self.activation=Softmax()
        self.cross_entropy_loss=Categorical_loss_entropy()
        
    def forward(self,inputs,y_true):
        self.activation.forward(inputs)
        self.outputs=self.activation.outputs
        return self.loss.calculate(self.outputs,y_true)  #the average loss
        
    def backward(self,dvalues,y_true):
        """deriving the loss with repsect to the inputs(outputs of softmax)."""
        self.dinputs=dvalues.copy()
        samples=len(dvalues)
        
        #check if the y_true is one hot encoded 
        if len(y_true.shape)==2:
            y_true=np.argmax(y_true,axis=1)

        self.dinputs[range(samples),y_true]-=1   #substract one from the value of the true class

        #lets normalize for the inputs
        self.dinputs=self.dinputs/samples
        #return self.dinputs

## Test Test Test between combined calculation of the activation and loss calculation

In [42]:
#seeding
#nnfs.init()
#seperate calculation of the softmax and loss
activation=Softmax()
loss=Categorical_loss_entropy()

softmax_outputs=np.array([
    [0.7,0.1,0.2],
    [0.1,0.5,0.4],
    [0.02,0.9,0.08]
])    #output for each inputs this is a batch of 3 inputs

true_values=np.array([0,1,1])

activation.outputs=softmax_outputs
#calculate the backward pass
loss.backward(softmax_outputs,true_values)
activation.backward(loss.dinputs)
dinputs1=activation.dinputs
print(dinputs1)

#all in one operation
softmax_cross_entropy=softmax_cross_entropy_loss()
softmax_cross_entropy.backward(softmax_outputs,true_values)
dinputs2=softmax_cross_entropy.dinputs
print(dinputs2)

[[-0.1         0.03333333  0.06666667]
 [ 0.03333333 -0.16666667  0.13333333]
 [ 0.00666667 -0.03333333  0.02666667]]
[[-0.1         0.03333333  0.06666667]
 [ 0.03333333 -0.16666667  0.13333333]
 [ 0.00666667 -0.03333333  0.02666667]]


## Time it..timing test

In [43]:
from timeit import timeit

In [44]:
softmax_outputs=np.array([
    [0.7,0.2,0.1],
    [0.1,0.5,0.4],
    [0.02,0.9,0.08]
])    #output for each inputs this is a batch of 3 inputs

true_values=np.array([0,1,1])

## lets time it 
def seperate_calculation():
    activation_fn=Softmax()
    loss=Categorical_loss_entropy()
    
    activation_fn.outputs=softmax_outputs
    #backpropagation
    loss.backward(softmax_outputs,true_values)
    activation.backward(loss.dinputs)
    dniputs=activation.dinputs

def all_in_one():
    act_loss=softmax_cross_entropy_loss()
    act_loss.backward(softmax_outputs,true_values)
    dinput2-act_loss.dinputs

#lets start the timing
t1=timeit(lambda:seperate_calculation,number=10000)
t2=timeit(lambda:all_in_one,number=10000)

print(f"the first time:{t1}")
print(f"the second time:{t2}")

the first time:0.0005750999999998285
the second time:0.0006941999999998671


# Full code implementation

In [45]:
from nnfs.datasets import spiral_data
from dense import Dense
from activation import Relu
from loss import softmax_categorical_loss

In [50]:
#define the architechtire
dense1=Dense(2,3)
activation=Relu()
dense2=Dense(3,3)
softmax_loss=softmax_categorical_loss()

#lets get the data
x,y=spiral_data(samples=1000,classes=3)

#the forward pass of the neural network
dense1.forward(x)
activation.forward(dense1.outputs)
dense2.forward(activation.output)

loss=softmax_loss.forward(dense2.outputs,y)

print(softmax_loss.outputs[:5])
#print(loss_v)

#lets check for the accuracy
prediction=np.argmax(softmax_loss.outputs,axis=1)
if len(y.shape)==2:
    y=np.argmax(y,axis=1)
    
accuracy=np.mean(prediction==y)
print(f"the accuracys:{accuracy:.4f}")

#lets start the backprop
softmax_loss.backward(softmax_loss.outputs,y)
dense2.backward(softmax_loss.dinputs)
activation.backward(dense2.dinputs)
dense1.backward(activation.drelu)

#lets print some values here
print(dense2.dinputs)
print(dense2.dweights)
print(dense2.dbias)

print(dense1.dinputs)
print(dense1.dweights)
print(dense1.dbias)

[[0.33333333 0.33333333 0.33333333]
 [0.33333332 0.33333334 0.33333334]
 [0.33333327 0.33333336 0.33333337]
 [0.33333333 0.33333333 0.33333333]
 [0.33333276 0.3333334  0.33333384]]
the accuracys:0.3200
[[ 3.44759462e-06  5.04246346e-06  4.99954418e-06]
 [ 3.44759467e-06  5.04246355e-06  4.99954425e-06]
 [ 3.44759493e-06  5.04246390e-06  4.99954465e-06]
 ...
 [-3.10018578e-06 -1.77329922e-06 -5.61497134e-06]
 [-3.10018578e-06 -1.77329922e-06 -5.61497134e-06]
 [-3.10018578e-06 -1.77329922e-06 -5.61497134e-06]]
[[-1.49657517e-04  1.26060368e-04  2.35971488e-05]
 [-2.19338525e-05 -2.52707366e-05  4.72045891e-05]
 [-1.26051655e-04  1.12613191e-04  1.34384646e-05]]
[[-2.38394806e-05  2.60734618e-06  2.12321344e-05]]
[[ 0.00000000e+00  0.00000000e+00]
 [ 2.72782623e-08  1.21979042e-08]
 [ 1.45923566e-07 -1.12819103e-08]
 ...
 [ 0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00]]
[[ 1.11579627e-04  1.59562228e-04  1.54700764e-04]
 [-4.27182840