In [38]:
import numpy as np

In [39]:
p=np.random.randn(10)

# simple implementation of RELU

In [40]:
output=[]

for i in p:
    if i>0:
        output.append(i)
    else:
        output.append(0)

In [41]:
print(output)

[0, 0.10945564193417558, 1.2456329939226953, 0, 0.4076127014231746, 1.3110234849051623, 0, 0.7211906997196429, 0, 0.8097696417947774]


# smarter way

In [42]:
outputs=[]
p_p=[0, 2, 0, -3.3, 0, 1.1, -2.2, 0]
p_a=np.array(p_p)
# for i in p_a:
#     outputs.append(max(0,i))  

p_a=np.maximum(0,p_a)

In [43]:
p_a

array([0. , 2. , 0. , 0. , 0. , 1.1, 0. , 0. ])

# lets make a class of RELU yay

In [44]:
from dense import Dense
from nnfs.datasets import spiral_data

In [45]:
class Relu_act:
    def forward(self,inputs):
        self.output=np.maximum(0,inputs)

In [46]:
x,y=spiral_data(samples=1000,classes=3)

#lets specify some architecture of the neural network
dense1=Dense(2,3)
activation_1=Relu_act()


#make forward pass into the model
dense1.forward(x)
#lets pass the output through the activation function
activation_1.forward(dense1.outputs)

#lets see some value after the activation function has passed 
print(activation_1.output[:5])

[[0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [6.10858151e-06 1.67238718e-05 5.24027948e-06]
 [3.52216323e-05 1.62705576e-05 5.09456273e-06]
 [4.79648162e-05 2.96840358e-05 9.29657477e-06]
 [7.91942843e-05 2.07965132e-05 6.50742009e-06]]


In [47]:
class Activation_ReLU:
# Forward pass
    def forward(self, inputs):
# Calculate output values from input
        self.output = np.maximum(0, inputs)


X, y = spiral_data(samples=100, classes=3)
# Create Dense layer with 2 input features and 3 output values
dense1 = Dense(2, 3)
# Create ReLU activation (to be used with Dense layer):
activation1 = Activation_ReLU()
# Make a forward pass of our training data through this layer
dense1.forward(X)
# Forward pass through activation func.
# Takes in output from previous layer
activation1.forward(dense1.outputs)

print(activation1.output[:5])


[[0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 5.28808205e-05 0.00000000e+00]
 [0.00000000e+00 8.16997343e-05 0.00000000e+00]
 [0.00000000e+00 2.01586401e-04 0.00000000e+00]
 [0.00000000e+00 3.70920765e-04 0.00000000e+00]]


# using softmax in output 

In [48]:
layer_output=[4.8,1.21,2.385]

E=2.71828182846  
output_exp=[]

for i in layer_output:
    output_exp.append(E**i)

print(layer_output)
print(output_exp)

[4.8, 1.21, 2.385]
[121.51041751893969, 3.3534846525504487, 10.85906266492961]


In [49]:
output_sum=np.sum(output_exp)

norm_output=[]
for i in range(len(output_exp)):
    norm_output.append(output_exp[i]/output_sum)

print(norm_output)

[0.8952826639573506, 0.024708306782070668, 0.08000902926057876]


In [50]:
np.sum(norm_output)   #this is the porbability distribution of numbers

1.0

## all in one step of Relu

In [51]:
layer_output=[4.8,1.21,2.385]

#lets first exponentiate the values

E=2.71828182846  
output_exp=[]

for i in layer_output:
    output_exp.append(E**i)

# lets divide the values with there sum
output_sum=np.sum(output_exp)

norm_output=[]
for i in range(len(output_exp)):
    norm_output.append(output_exp[i]/output_sum)

print(f"the exponentiated values:{output_exp}.")
print(f"lets get the probability distribution from the values:{norm_output} ")
print(f"lets check for summation of probability distribution:{np.sum(norm_output)} ")

the exponentiated values:[121.51041751893969, 3.3534846525504487, 10.85906266492961].
lets get the probability distribution from the values:[0.8952826639573506, 0.024708306782070668, 0.08000902926057876] 
lets check for summation of probability distribution:1.0 


# lets try again using numpy

In [52]:
output_layer=[4.8,1.21,2.385]
output_exp=np.exp(output_layer)

prob_dist=[]
#lets get the probability distribution the norm distribution
prob_dist=output_exp/np.sum(output_exp)

print(prob_dist)
print(np.sum(prob_dist))

[0.89528266 0.02470831 0.08000903]
0.9999999999999999


# layer output in batches

## play ground

In [53]:
p=[
    [1,2,3,4],
    [5,6,7,8],
    [10,11,12,13]
]

p_a=np.array(p)

# summation of rows

In [54]:
np.sum(p,axis=1)

array([10, 26, 46])

In [55]:
for i in p:
    print(sum(i))

10
26
46


In [56]:
sum([12,32,43])

87

# summation of columns

In [57]:
np.sum(p,axis=0)

array([16, 19, 22, 25])

### the implementation of summing along columns

In [58]:
summ=[]
for i in p_a.T:
    summ.append(sum(i.T))

In [59]:
summ

[16, 19, 22, 25]

In [60]:
np.sum(p_a,axis=1,keepdims=True)

array([[10],
       [26],
       [46]])

In [61]:
layer_outputs = np.array([[4.8, 1.21, 2.385],
                            [8.9, -1.81, 0.2],
                            [1.41, 1.051, 0.026]])

summation=np.sum(layer_outputs,axis=1,keepdims=True)

In [62]:
summation.shape,layer_outputs.shape

((3, 1), (3, 3))

In [63]:
temp=np.sum(layer_outputs,axis=1)

# lets implement the SOFTMAX

### sample of exploading value of Softmax

In [64]:
np.exp(200)

7.225973768125749e+86

In [65]:
np.exp(10)

22026.465794806718

In [66]:
print(np.exp(1000))

inf


C:\Users\nebiy\AppData\Local\Temp\ipykernel_4768\2528843860.py:1: RuntimeWarning: overflow encountered in exp
  print(np.exp(1000))


## implementation time

In [67]:
np.max(p_a,axis=1)

array([ 4,  8, 13])

In [68]:
class Softmax:
    def forward(self,inputs):
        #we are scaling the value
        self.scaled=np.exp(inputs - np.max(inputs,axis=1,keepdims=True))
        #lets get probability distribution
        self.outputs=self.scaled/np.sum(self.scaled,axis=1,keepdims=True)
        return self.outputs

In [69]:
act_soft=Softmax()
act_soft.forward(layer_outputs)
print(act_soft.scaled)
print()
print(act_soft.outputs)
print()
print(np.sum(act_soft.outputs,axis=1))

[[1.00000000e+00 2.75983304e-02 8.93673389e-02]
 [1.00000000e+00 2.23206120e-05 1.66585811e-04]
 [1.00000000e+00 6.98374351e-01 2.50574249e-01]]

[[8.95282664e-01 2.47083068e-02 8.00090293e-02]
 [9.99811129e-01 2.23163963e-05 1.66554348e-04]
 [5.13097164e-01 3.58333899e-01 1.28568936e-01]]

[1. 1. 1.]


In [70]:
# lets try on one dim
a=[1,2,3]
act_2=Softmax()
act_2.forward([a])
print(act_2.outputs)

[[0.09003057 0.24472847 0.66524096]]


In [71]:
act_2.scaled

array([[0.13533528, 0.36787944, 1.        ]])

In [72]:
act_2.forward([[-2,-1,0]])
print(act_2.outputs)

[[0.09003057 0.24472847 0.66524096]]


# lets put it all together and make a some deep neural network

In [73]:
#lets get our input that has 3 classes and 2 input features
x,y=spiral_data(samples=1000,classes=3)

#lets first hiddden layer 
dense1=Dense(2,3)

#lets use relu for hidden layer
act1=Activation_ReLU()

#the last layer hidden network
dense2=Dense(3,3)

#lets use softmax as the head of the deep neural network
act2=Softmax()

In [74]:
# lets train it
dense1.forward(x)

#pass it through activation function
act1.forward(dense1.outputs)

#lets give pass it through our last layer
dense2.forward(act1.output)

#throug our softmax layer
act2.forward(dense2.outputs)

print(act2.outputs[:10])

[[0.33333333 0.33333333 0.33333333]
 [0.33333334 0.33333333 0.33333334]
 [0.33333332 0.3333333  0.33333338]
 [0.33333333 0.33333331 0.33333335]
 [0.33333338 0.33333337 0.33333325]
 [0.3333333  0.33333327 0.33333343]
 [0.33333342 0.3333334  0.33333318]
 [0.33333343 0.33333341 0.33333316]
 [0.33333332 0.33333326 0.33333342]
 [0.33333333 0.33333327 0.3333334 ]]
